# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiteat', '0005_auto_20170906_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
    ]
