# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiteat', '0007_remove_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
