# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiteat', '0011_auto_20170906_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
