# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiteat', '0015_auto_20170906_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=100.0),
        ),
    ]
